"""reference and market data tables

Revision ID: 354672f0f639
Revises: 
Create Date: 2026-08-04 15:15:32.546779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '354672f0f639'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rates',
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('pair', sa.String(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.PrimaryKeyConstraint('as_of', 'pair')
    )
    op.create_table('instruments',
    sa.Column('instrument_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('segment', sa.Enum('nse_stock', 'nse_index', 'us_stock', 'us_index', name='segment_enum'), nullable=True),
    sa.Column('kind', sa.Enum('underlying', 'index', 'option', 'future', name='instrument_kind'), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('underlying_id', sa.BigInteger(), nullable=True),
    sa.Column('strike', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('option_type', sa.String(length=1), nullable=True),
    sa.Column('expiry', sa.Date(), nullable=True),
    sa.Column('exercise_style', sa.String(), nullable=True),
    sa.Column('settlement', sa.String(), nullable=True),
    sa.Column('provider_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['underlying_id'], ['instruments.instrument_id'], ),
    sa.PrimaryKeyConstraint('instrument_id'),
    sa.UniqueConstraint('exchange', 'symbol', 'expiry', 'strike', 'option_type', name='uq_instrument_identity')
    )
    op.create_table('trading_calendar',
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('is_holiday', sa.Boolean(), nullable=False),
    sa.Column('open_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tz', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('exchange', 'session_date')
    )
    op.create_table('chain_snapshots',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('underlying_id', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('contract_count', sa.Integer(), nullable=False),
    sa.Column('expected_count', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['underlying_id'], ['instruments.instrument_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_table('corporate_actions',
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('ratio', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('adj_factor', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ),
    sa.PrimaryKeyConstraint('instrument_id', 'ex_date', 'action_type')
    )
    op.create_table('instrument_specs',
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('tick_size', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ),
    sa.PrimaryKeyConstraint('instrument_id', 'valid_from')
    )
    op.create_table('market_depth',
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('side', sa.String(length=1), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('orders', sa.Integer(), nullable=True),
    sa.CheckConstraint("side IN ('B','S')", name='ck_depth_side'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ),
    sa.PrimaryKeyConstraint('instrument_id', 'ts', 'side', 'level')
    )
    op.create_table('option_quotes',
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=True),
    sa.Column('bid', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('ask', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('bid_sz', sa.Integer(), nullable=True),
    sa.Column('ask_sz', sa.Integer(), nullable=True),
    sa.Column('ltp', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('oi', sa.BigInteger(), nullable=True),
    sa.Column('oi_change', sa.BigInteger(), nullable=True),
    sa.Column('underlying_px', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('iv', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('delta', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('gamma', sa.Numeric(precision=14, scale=10), nullable=True),
    sa.Column('theta', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('vega', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('rho', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('greeks_model', sa.String(), nullable=True),
    sa.Column('greeks_inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vendor_iv', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('tier', sa.SmallInteger(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('quality', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ),
    sa.PrimaryKeyConstraint('instrument_id', 'ts')
    )
    op.create_table('options_flow',
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('premium', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('aggressor', sa.String(length=1), nullable=True),
    sa.Column('greeks_at_print', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ),
    sa.PrimaryKeyConstraint('instrument_id', 'ts', 'price', 'size')
    )
    op.create_table('underlying_bars',
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('vwap', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('quality', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ),
    sa.PrimaryKeyConstraint('instrument_id', 'timeframe', 'ts')
    )
    op.create_table('watchlist_membership',
    sa.Column('segment', sa.Enum('nse_stock', 'nse_index', 'us_stock', 'us_index', name='segment_enum'), nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('tier', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ),
    sa.PrimaryKeyConstraint('segment', 'instrument_id', 'valid_from')
    )
    # ### end Alembic commands ###

    # --- Hypertable conversion + compression/retention policies -----------
    # Not expressible via SQLAlchemy's DDL — see ARCHITECTURE.md §5.2, §6.
    op.execute(
        "SELECT create_hypertable('underlying_bars', 'ts', "
        "chunk_time_interval => interval '7 days')"
    )

    op.execute(
        "SELECT create_hypertable('option_quotes', 'ts', "
        "chunk_time_interval => interval '1 day')"
    )
    op.execute(
        "ALTER TABLE option_quotes SET ("
        "timescaledb.compress, "
        "timescaledb.compress_segmentby = 'instrument_id', "
        "timescaledb.compress_orderby = 'ts DESC')"
    )
    op.execute("SELECT add_compression_policy('option_quotes', interval '7 days')")

    # T2 only, 30-day retention, no exception (ARCHITECTURE.md §6).
    op.execute(
        "SELECT create_hypertable('market_depth', 'ts', "
        "chunk_time_interval => interval '1 day')"
    )
    op.execute("SELECT add_retention_policy('market_depth', interval '30 days')")

    op.execute(
        "SELECT create_hypertable('options_flow', 'ts', "
        "chunk_time_interval => interval '7 days')"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_membership')
    op.drop_table('underlying_bars')
    op.drop_table('options_flow')
    op.drop_table('option_quotes')
    op.drop_table('market_depth')
    op.drop_table('instrument_specs')
    op.drop_table('corporate_actions')
    op.drop_table('chain_snapshots')
    op.drop_table('trading_calendar')
    op.drop_table('instruments')
    op.drop_table('fx_rates')
    # ### end Alembic commands ###

    # Autogenerate doesn't emit these for postgres ENUM types (known gap).
    op.execute("DROP TYPE segment_enum")
    op.execute("DROP TYPE instrument_kind")
